Match and improve installl scripts

diff --git a/.github/workflows/base_node_binaries.yml b/.github/workflows/base_node_binaries.yml
--- a/.github/workflows/base_node_binaries.yml
+++ b/.github/workflows/base_node_binaries.yml
@@ -7,7 +7,7 @@ on:
     branches:
       - build-*
   schedule:
-    - cron: "05 00 * * *"
+    - cron: "05 00 * * 1"
   workflow_dispatch:
     inputs:
       customTag:
@@ -16,7 +16,7 @@ on:
         default: "development-tag"
 
 env:
-  TBN_FILENAME: "tari_base_node"
+  TBN_FILENAME: "tari_suite"
 
 jobs:
   builds:
@@ -24,7 +24,8 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-18.04, macos-10.15, windows-2019]
+#        os: [ubuntu-18.04, macos-10.15, windows-2019]
+        os: [macos-10.15]
         # https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html
         target_cpu: ["x86-64"]
         # https://github.com/zkcrypto/curve25519-dalek-ng/pull/14
@@ -135,16 +136,7 @@ jobs:
           echo "C:\Strawberry\perl\bin" >> $GITHUB_PATH
 
       - name: Cache cargo files and outputs
-        uses: actions/cache@v2
-        with:
-          path: |
-            ~/.cargo/registry
-            ~/.cargo/git
-            target
-          key: ${{ runner.os }}-${{ matrix.os }}-${{ matrix.target_cpu }}-${{ matrix.features }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-${{ matrix.os }}-${{ matrix.target_cpu }}-${{ matrix.features }}-cargo-build-target-
-            ${{ runner.os }}-${{ matrix.os }}-${{ matrix.target_cpu }}-${{ matrix.features }}-
+        uses: Swatinem/rust-cache@v1
 
       - name: Compile launchpad GUI
         run: |
@@ -169,7 +161,6 @@ jobs:
           RUSTFLAGS: "-C target_cpu=${{ matrix.target_cpu }}"
           ROARING_ARCH: "${{ matrix.target_cpu }}"
         run: |
-          echo "Cache Key: ${{ runner.os }}-${{ matrix.os }}-${{ matrix.target_cpu }}-${{ matrix.features }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}"
           cargo build --release
 
       - name: Info - Post-Compile Space Check for Nix
@@ -212,6 +203,9 @@ jobs:
           MACOS_INSTALLER_ID: ${{ secrets.MACOS_INSTALLER_ID }}
           MACOS_INSTALLER_CERT: ${{ secrets.MACOS_INSTALLER_CERT }}
           MACOS_INSTALLER_PASS: ${{ secrets.MACOS_INSTALLER_PASS }}
+          MACOS_NOTARIZE_USERNAME: ${{ secrets.MACOS_NOTARIZE_USERNAME }}
+          MACOS_NOTARIZE_PASSWORD: ${{ secrets.MACOS_NOTARIZE_PASSWORD }}
+          MACOS_ASC_PROVIDER: ${{ secrets.MACOS_ASC_PROVIDER }}
         run: |
           echo $MACOS_APPLICATION_CERT | base64 --decode > application.p12
           echo $MACOS_INSTALLER_CERT | base64 --decode > installer.p12
@@ -233,25 +227,57 @@ jobs:
             "tari_launchpad"
           )
           for FILE in "${FILES[@]}"; do
-            codesign --force -s "Developer ID Application: $MACOS_APPLICATION_ID" "/tmp/tari_testnet/runtime/$FILE" -v
+            codesign --options runtime --force --verify --verbose --sign "Developer ID Application: $MACOS_APPLICATION_ID" "/tmp/tari_testnet/runtime/$FILE"
             codesign --verify --deep --display --verbose=4 "/tmp/tari_testnet/runtime/$FILE"
             cp -vf "/tmp/tari_testnet/runtime/$FILE" "$GITHUB_WORKSPACE${{ env.TBN_DIST }}"
           done
           pkgbuild --root /tmp/tari_testnet \
-          --identifier "com.tarilabs.pkg" \
-          --version "$VERSION" \
-          --install-location "/tmp/tari" \
-          --scripts "/tmp/tari_testnet/scripts" \
-          --sign "Developer ID Installer: $MACOS_INSTALLER_ID" \
-          "${{ github.workspace }}${{ env.TBN_DIST }}/tari-${{ env.VERSION }}.pkg"
+            --identifier "com.tarilabs.pkg.${{ env.TBN_FILENAME }}" \
+            --version "$VERSION" \
+            --install-location "/tmp/tari" \
+            --scripts "/tmp/tari_testnet/scripts" \
+            --sign "Developer ID Installer: $MACOS_INSTALLER_ID" \
+            "${{ github.workspace }}${{ env.TBN_DIST }}/${{ env.TBN_FILENAME }}-${{ env.VERSION }}.pkg"
+          echo -e "Submitting to Apple...\n\n"
+          xcrun altool --notarize-app \
+            --primary-bundle-id "com.tarilabs.pkg.tari.suite" \
+            --username "$MACOS_NOTARIZE_USERNAME" --password "$MACOS_NOTARIZE_PASSWORD" \
+            --asc-provider "$MACOS_ASC_PROVIDER" \
+            --file "${{ github.workspace }}${{ env.TBN_DIST }}/${{ env.TBN_FILENAME }}-${{ env.VERSION }}.pkg" &> notarisation.result
+          requestUUID=`grep RequestUUID notarisation.result | cut -d" " -f 3`
+          echo $requestUUID
+          if [[ $requestUUID == "" ]]; then
+            echo "could not upload for notarization"
+            exit 1
+          else
+            echo "Notarization RequestUUID: $requestUUID"
+          fi
+          echo -e "\n\nChecking result of notarisation..."
+          request_status="in progress"
+          while [[ "$request_status" == "in progress" ]]; do
+            echo -n "waiting... "
+            sleep 10
+            request_status=$(xcrun altool --notarization-info $requestUUID --username "$MACOS_NOTARIZE_USERNAME" --password "$MACOS_NOTARIZE_PASSWORD" 2>&1)
+            echo "$request_status"
+            request_status=$(echo "$request_status" | awk -F ': ' '/Status:/ { print $2; }' )
+            echo "$request_status"
+          done
+          echo "$request_status"
+          if [[ $request_status != "success" ]]; then
+            echo "## could not notarize - $request_status - ${{ env.TBN_FILENAME }}-${{ env.VERSION }}.pkg"
+            exit 1
+          else
+            echo -e "\nStapling package...${{ env.TBN_FILENAME }}-${{ env.VERSION }}.pkg\n"
+            xcrun stapler staple -v "${{ github.workspace }}${{ env.TBN_DIST }}/${{ env.TBN_FILENAME }}-${{ env.VERSION }}.pkg"
+          fi
 
       - name: Artifact upload for macOS pkg
         if: startsWith(runner.os,'macOS')
         continue-on-error: true
         uses: actions/upload-artifact@v2
         with:
-          name: tari-${{ env.VERSION }}.pkg
-          path: "${{ github.workspace }}${{ env.TBN_DIST }}/tari-${{ env.VERSION }}.pkg"
+          name: ${{ env.TBN_FILENAME }}-${{ env.VERSION }}.pkg
+          path: "${{ github.workspace }}${{ env.TBN_DIST }}/${{ env.TBN_FILENAME }}-${{ env.VERSION }}.pkg"
 
       # unlike inno script studio, iscc.exe doesn't run the [precompile] step generate_config.bat
       - name: Build the Windows installer
